// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjmVrfO3tXN-Ds-GjdueM42fiYXRk_Ssk',
    appId: '1:163922478386:web:e5781c0ee7ad71fe9b032b',
    messagingSenderId: '163922478386',
    projectId: 'apptitude-ace-network',
    authDomain: 'apptitude-ace-network.firebaseapp.com',
    storageBucket: 'apptitude-ace-network.appspot.com',
    measurementId: 'G-1C8Y3CBNPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzPBWQSEEPSiMoelq1IGqrBm2wpO6qjrw',
    appId: '1:163922478386:android:53040417dad77a449b032b',
    messagingSenderId: '163922478386',
    projectId: 'apptitude-ace-network',
    storageBucket: 'apptitude-ace-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByF3NW-VbisDo2fHyXbncbpWZEjleaKNM',
    appId: '1:163922478386:ios:1d6577b2debf40de9b032b',
    messagingSenderId: '163922478386',
    projectId: 'apptitude-ace-network',
    storageBucket: 'apptitude-ace-network.appspot.com',
    iosBundleId: 'com.example.apptitudeAceNetwork',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByF3NW-VbisDo2fHyXbncbpWZEjleaKNM',
    appId: '1:163922478386:ios:e19c6f8384b1127d9b032b',
    messagingSenderId: '163922478386',
    projectId: 'apptitude-ace-network',
    storageBucket: 'apptitude-ace-network.appspot.com',
    iosBundleId: 'com.example.apptitudeAceNetwork.RunnerTests',
  );
}
